name = "La survie de zinzin"
author = "Mr_Shampoing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86d53fec263f71ab30caa321ecdee02af0a3c2b301425c21aa9cf8ec840d340f"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
