name = "La survie de zinzin"
author = "Mr_Shampoing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69caec3632e7429f26164c6e00920a498f33983ee1d667452d118af89da4b09a"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
