name = "La survie de zinzin"
author = "Mr_Shampoing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "658f646113a7f729a70abd5744d901d517b479e2b74b64d4fa714aec34e437c8"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
